-- ========================================
-- FARMTECH SOLUTIONS - BANCO DE DADOS
-- Sistema de Monitoramento de Sensores
-- ========================================

-- Criar tabela de tipos de sensores
CREATE TABLE Tipo_Sensor (
    id_tipo_sensor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL UNIQUE,
    unidade_medida VARCHAR2(20) NOT NULL,
    valor_minimo NUMBER(10,2),
    valor_maximo NUMBER(10,2),
    descricao VARCHAR2(200)
);

-- Criar tabela de culturas
CREATE TABLE Cultura (
    id_cultura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    temp_min_ideal NUMBER(5,2),
    temp_max_ideal NUMBER(5,2),
    umidade_min_ideal NUMBER(5,2),
    umidade_max_ideal NUMBER(5,2),
    descricao VARCHAR2(500)
);

-- Criar tabela de equipamentos
CREATE TABLE Equipamento (
    id_equipamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    localizacao VARCHAR2(100),
    id_cultura NUMBER,
    data_instalacao DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'Ativo' CHECK (status IN ('Ativo', 'Inativo', 'Manutenção')),
    CONSTRAINT fk_cultura FOREIGN KEY (id_cultura) REFERENCES Cultura(id_cultura)
);

-- Criar tabela de sensores
CREATE TABLE Sensor (
    id_sensor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_sensor NUMBER NOT NULL,
    id_equipamento NUMBER,
    modelo VARCHAR2(50),
    fabricante VARCHAR2(50),
    data_instalacao DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'Ativo' CHECK (status IN ('Ativo', 'Inativo', 'Manutenção')),
    intervalo_leitura NUMBER DEFAULT 60,
    CONSTRAINT fk_tipo_sensor FOREIGN KEY (id_tipo_sensor) REFERENCES Tipo_Sensor(id_tipo_sensor),
    CONSTRAINT fk_equipamento FOREIGN KEY (id_equipamento) REFERENCES Equipamento(id_equipamento)
);

-- Criar tabela de leituras
CREATE TABLE Leitura (
    id_leitura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sensor NUMBER NOT NULL,
    valor NUMBER(10,2) NOT NULL,
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    qualidade VARCHAR2(20) DEFAULT 'Normal' CHECK (qualidade IN ('Normal', 'Alerta', 'Crítico')),
    CONSTRAINT fk_sensor FOREIGN KEY (id_sensor) REFERENCES Sensor(id_sensor),
    CONSTRAINT chk_valor CHECK (valor >= -100 AND valor <= 200)
);

-- Criar tabela de alertas
CREATE TABLE Alerta (
    id_alerta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_leitura NUMBER NOT NULL,
    tipo_alerta VARCHAR2(50) NOT NULL,
    mensagem VARCHAR2(500),
    data_alerta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolvido CHAR(1) DEFAULT 'N' CHECK (resolvido IN ('S', 'N')),
    data_resolucao TIMESTAMP,
    CONSTRAINT fk_leitura_alerta FOREIGN KEY (id_leitura) REFERENCES Leitura(id_leitura)
);

-- Criar índices para melhor performance
CREATE INDEX idx_leitura_sensor ON Leitura(id_sensor);
CREATE INDEX idx_leitura_data ON Leitura(data_hora);
CREATE INDEX idx_sensor_tipo ON Sensor(id_tipo_sensor);
CREATE INDEX idx_sensor_equip ON Sensor(id_equipamento);
CREATE INDEX idx_alerta_leitura ON Alerta(id_leitura);

-- ========================================
-- INSERÇÃO DE DADOS INICIAIS
-- ========================================

-- Inserir tipos de sensores
INSERT INTO Tipo_Sensor (nome, unidade_medida, valor_minimo, valor_maximo, descricao) 
VALUES ('Temperatura', '°C', -10, 50, 'Sensor de temperatura ambiente');

INSERT INTO Tipo_Sensor (nome, unidade_medida, valor_minimo, valor_maximo, descricao) 
VALUES ('Umidade', '%', 0, 100, 'Sensor de umidade relativa do ar');

INSERT INTO Tipo_Sensor (nome, unidade_medida, valor_minimo, valor_maximo, descricao) 
VALUES ('pH Solo', 'pH', 0, 14, 'Sensor de pH do solo');

INSERT INTO Tipo_Sensor (nome, unidade_medida, valor_minimo, valor_maximo, descricao) 
VALUES ('Luminosidade', 'lux', 0, 100000, 'Sensor de intensidade luminosa');

INSERT INTO Tipo_Sensor (nome, unidade_medida, valor_minimo, valor_maximo, descricao) 
VALUES ('Umidade Solo', '%', 0, 100, 'Sensor de umidade do solo');

-- Inserir culturas
INSERT INTO Cultura (nome, temp_min_ideal, temp_max_ideal, umidade_min_ideal, umidade_max_ideal, descricao)
VALUES ('Tomate', 18, 25, 60, 70, 'Cultura de tomates em estufa');

INSERT INTO Cultura (nome, temp_min_ideal, temp_max_ideal, umidade_min_ideal, umidade_max_ideal, descricao)
VALUES ('Alface', 15, 22, 65, 75, 'Cultura de alface hidropônica');

INSERT INTO Cultura (nome, temp_min_ideal, temp_max_ideal, umidade_min_ideal, umidade_max_ideal, descricao)
VALUES ('Morango', 15, 23, 60, 70, 'Cultura de morangos em estufa');

-- Inserir equipamentos
INSERT INTO Equipamento (nome, localizacao, id_cultura, status) 
VALUES ('Estufa 1', 'Setor A - Norte', 1, 'Ativo');

INSERT INTO Equipamento (nome, localizacao, id_cultura, status) 
VALUES ('Estufa 2', 'Setor A - Sul', 1, 'Ativo');

INSERT INTO Equipamento (nome, localizacao, id_cultura, status) 
VALUES ('Estufa 3', 'Setor B - Leste', 2, 'Ativo');

INSERT INTO Equipamento (nome, localizacao, id_cultura, status) 
VALUES ('Estufa 4', 'Setor B - Oeste', 3, 'Ativo');

-- Inserir sensores
-- Estufa 1
INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (1, 1, 'DHT22', 'Aosong', 60);

INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (2, 1, 'DHT22', 'Aosong', 60);

INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (5, 1, 'YL-69', 'Generic', 300);

-- Estufa 2
INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (1, 2, 'DS18B20', 'Dallas', 60);

INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (2, 2, 'HIH-4030', 'Honeywell', 60);

-- Estufa 3
INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (1, 3, 'DHT22', 'Aosong', 60);

INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (2, 3, 'DHT22', 'Aosong', 60);

INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (4, 3, 'BH1750', 'ROHM', 120);

-- Estufa 4
INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (1, 4, 'BME280', 'Bosch', 60);

INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura) 
VALUES (2, 4, 'BME280', 'Bosch', 60);

-- Commit das transações
COMMIT;
