#!/usr/bin/env python3
"""
Script para criar banco SQLite limpo - apenas estrutura base sem leituras históricas
"""

import sqlite3
import re
from pathlib import Path

# Caminhos
DB_PATH = Path(__file__).parent.parent / 'data' / 'farmtech.db'
SQL_SCHEMA = Path(__file__).parent.parent / 'db' / 'banco.sql'

def convert_oracle_to_sqlite(sql_content):
    """Converte SQL do Oracle para SQLite"""

    # Primeiro, substituir GENERATED BY DEFAULT AS IDENTITY (antes de converter NUMBER)
    sql_content = re.sub(
        r'NUMBER\s+GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY\s+PRIMARY\s+KEY',
        'INTEGER PRIMARY KEY AUTOINCREMENT',
        sql_content, flags=re.IGNORECASE
    )

    # Substituir DATE DEFAULT SYSDATE com marcador temporário
    sql_content = re.sub(
        r'DATE\s+DEFAULT\s+SYSDATE',
        "___SQLITE_DATE_NOW___",
        sql_content, flags=re.IGNORECASE
    )

    # Substituir TIMESTAMP DEFAULT CURRENT_TIMESTAMP com marcador temporário
    sql_content = re.sub(
        r'TIMESTAMP\s+DEFAULT\s+CURRENT_TIMESTAMP',
        "___SQLITE_DATETIME_NOW___",
        sql_content, flags=re.IGNORECASE
    )

    # Substituir tipos numéricos
    sql_content = re.sub(r'NUMBER\(\d+,\s*\d+\)', 'REAL', sql_content, flags=re.IGNORECASE)
    sql_content = re.sub(r'NUMBER\(\d+\)', 'INTEGER', sql_content, flags=re.IGNORECASE)
    sql_content = re.sub(r'\bNUMBER\b', 'INTEGER', sql_content, flags=re.IGNORECASE)

    # Substituir VARCHAR2/CHAR por TEXT (sem preservar tamanho)
    sql_content = re.sub(r'VARCHAR2\(\d+\)', 'TEXT', sql_content, flags=re.IGNORECASE)
    sql_content = re.sub(r'CHAR\(\d+\)', 'TEXT', sql_content, flags=re.IGNORECASE)

    # Substituir tipos de data/hora restantes
    sql_content = re.sub(r'\bTIMESTAMP\b', 'TEXT', sql_content, flags=re.IGNORECASE)
    sql_content = re.sub(r'\bDATE\b', 'TEXT', sql_content, flags=re.IGNORECASE)

    # Restaurar marcadores com valores corretos do SQLite
    sql_content = sql_content.replace("___SQLITE_DATE_NOW___", "TEXT DEFAULT (date('now'))")
    sql_content = sql_content.replace("___SQLITE_DATETIME_NOW___", "TEXT DEFAULT (datetime('now', 'localtime'))")

    # Remover comandos específicos do Oracle
    sql_content = re.sub(r'COMMIT;', '', sql_content, flags=re.IGNORECASE)

    return sql_content

def create_database():
    """Cria o banco SQLite com apenas estrutura base"""

    print("🗄️  Criando banco de dados limpo...")

    # Remover banco existente
    if DB_PATH.exists():
        DB_PATH.unlink()
        print(f"   Banco anterior removido: {DB_PATH}")

    # Criar diretório se não existir
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Ler e converter schema
    print("📋 Lendo schema do Oracle...")
    with open(SQL_SCHEMA, 'r', encoding='utf-8') as f:
        oracle_schema = f.read()

    sqlite_schema = convert_oracle_to_sqlite(oracle_schema)

    # Criar banco e executar schema
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    print("🔨 Criando tabelas...")

    # Separar CREATE TABLE statements
    create_tables = re.findall(
        r'CREATE\s+TABLE\s+.*?\);',
        sqlite_schema,
        re.DOTALL | re.IGNORECASE
    )

    for statement in create_tables:
        statement = statement.strip()
        if statement:
            try:
                cursor.execute(statement)
                table_name = re.search(r'CREATE\s+TABLE\s+(\w+)', statement, re.IGNORECASE)
                if table_name:
                    print(f"   ✓ Tabela {table_name.group(1)} criada")
            except sqlite3.Error as e:
                print(f"   ⚠️  Erro ao criar tabela: {e}")

    # Separar CREATE INDEX statements
    create_indexes = re.findall(
        r'CREATE\s+INDEX\s+.*?;',
        sqlite_schema,
        re.DOTALL | re.IGNORECASE
    )

    for statement in create_indexes:
        statement = statement.strip()
        if statement:
            try:
                cursor.execute(statement)
            except sqlite3.Error as e:
                pass  # Ignorar erros de índice

    conn.commit()
    print("✅ Estrutura criada com sucesso!")

    # Inserir dados iniciais manualmente
    print("🌱 Inserindo dados base...")

    # Tipos de Sensor
    cursor.executemany("""
        INSERT INTO Tipo_Sensor (nome, unidade_medida, valor_minimo, valor_maximo, descricao)
        VALUES (?, ?, ?, ?, ?)
    """, [
        ('Temperatura', '°C', -10, 50, 'Sensor de temperatura ambiente'),
        ('Umidade', '%', 0, 100, 'Sensor de umidade relativa do ar'),
        ('pH Solo', 'pH', 0, 14, 'Sensor de pH do solo'),
        ('Luminosidade', 'lux', 0, 100000, 'Sensor de intensidade luminosa'),
        ('Umidade Solo', '%', 0, 100, 'Sensor de umidade do solo')
    ])

    # Culturas
    cursor.executemany("""
        INSERT INTO Cultura (nome, temp_min_ideal, temp_max_ideal, umidade_min_ideal, umidade_max_ideal, descricao)
        VALUES (?, ?, ?, ?, ?, ?)
    """, [
        ('Tomate', 18, 25, 60, 70, 'Cultura de tomates em estufa'),
        ('Alface', 15, 22, 65, 75, 'Cultura de alface hidropônica'),
        ('Morango', 15, 23, 60, 70, 'Cultura de morangos em estufa')
    ])

    # Equipamentos
    cursor.executemany("""
        INSERT INTO Equipamento (nome, localizacao, id_cultura, status)
        VALUES (?, ?, ?, ?)
    """, [
        ('Estufa 1', 'Setor A - Norte', 1, 'Ativo'),
        ('Estufa 2', 'Setor A - Sul', 1, 'Ativo'),
        ('Estufa 3', 'Setor B - Leste', 2, 'Ativo'),
        ('Estufa 4', 'Setor B - Oeste', 3, 'Ativo')
    ])

    # Sensores
    cursor.executemany("""
        INSERT INTO Sensor (id_tipo_sensor, id_equipamento, modelo, fabricante, intervalo_leitura)
        VALUES (?, ?, ?, ?, ?)
    """, [
        # Estufa 1
        (1, 1, 'DHT22', 'Aosong', 60),
        (2, 1, 'DHT22', 'Aosong', 60),
        (5, 1, 'YL-69', 'Generic', 300),
        # Estufa 2
        (1, 2, 'DS18B20', 'Dallas', 60),
        (2, 2, 'HIH-4030', 'Honeywell', 60),
        # Estufa 3
        (1, 3, 'DHT22', 'Aosong', 60),
        (2, 3, 'DHT22', 'Aosong', 60),
        (4, 3, 'BH1750', 'ROHM', 120),
        # Estufa 4
        (1, 4, 'BME280', 'Bosch', 60),
        (2, 4, 'BME280', 'Bosch', 60)
    ])

    conn.commit()
    print("✅ Dados base inseridos!")

    # Renomear tabelas originais
    cursor.execute("ALTER TABLE Leitura RENAME TO Leitura_Base")
    cursor.execute("ALTER TABLE Alerta RENAME TO Alerta_Base")

    # Criar VIEW Leitura com colunas adicionais
    cursor.execute("""
        CREATE VIEW Leitura AS
        SELECT
            l.id_leitura,
            l.id_sensor,
            ts.nome as tipo_sensor,
            l.valor,
            l.data_hora,
            l.qualidade,
            e.nome as equipamento
        FROM Leitura_Base l
        JOIN Sensor s ON l.id_sensor = s.id_sensor
        JOIN Tipo_Sensor ts ON s.id_tipo_sensor = ts.id_tipo_sensor
        LEFT JOIN Equipamento e ON s.id_equipamento = e.id_equipamento
    """)

    # Criar VIEW Alerta com colunas renomeadas
    cursor.execute("""
        CREATE VIEW Alerta AS
        SELECT
            a.id_alerta,
            a.id_leitura,
            a.mensagem as descricao,
            CASE
                WHEN a.tipo_alerta LIKE '%Crítico%' OR a.tipo_alerta LIKE '%Critico%' THEN 'Critico'
                WHEN a.tipo_alerta LIKE '%Alerta%' THEN 'Alerta'
                ELSE 'Normal'
            END as nivel_severidade,
            a.data_alerta as data_hora_alerta,
            a.resolvido
        FROM Alerta_Base a
    """)

    conn.commit()
    print("✅ VIEWs criadas!")

    # Estatísticas
    print("\n📈 Banco limpo criado:")

    cursor.execute("SELECT COUNT(*) FROM Tipo_Sensor")
    print(f"   Tipos de Sensor: {cursor.fetchone()[0]}")

    cursor.execute("SELECT COUNT(*) FROM Cultura")
    print(f"   Culturas: {cursor.fetchone()[0]}")

    cursor.execute("SELECT COUNT(*) FROM Equipamento")
    print(f"   Equipamentos: {cursor.fetchone()[0]}")

    cursor.execute("SELECT COUNT(*) FROM Sensor")
    print(f"   Sensores: {cursor.fetchone()[0]}")

    cursor.execute("SELECT COUNT(*) FROM Leitura")
    print(f"   Leituras: {cursor.fetchone()[0]} (vazio)")

    cursor.execute("SELECT COUNT(*) FROM Alerta")
    print(f"   Alertas: {cursor.fetchone()[0]} (vazio)")

    conn.close()
    print(f"\n✅ Banco limpo criado: {DB_PATH}")
    print("🎯 Pronto para simulação em tempo real!")

if __name__ == '__main__':
    create_database()
